INSERT comunas VALUES(null,'Rancagua',6);
INSERT comunas VALUES(null,'Codegua',6);
INSERT comunas VALUES(null,'Coinco',6);
INSERT comunas VALUES(null,'Coltauco',6);
INSERT comunas VALUES(null,'Doñihue',6);
INSERT comunas VALUES(null,'Graneros',6);
INSERT comunas VALUES(null,'Las Cabras',6);
INSERT comunas VALUES(null,'Machalí',6);
INSERT comunas VALUES(null,'Malloa',6);
INSERT comunas VALUES(null,'Mostazal',6);
INSERT comunas VALUES(null,'Olivar',6);
INSERT comunas VALUES(null,'Peumo',6);
INSERT comunas VALUES(null,'Pichidegua',6);
INSERT comunas VALUES(null,'Quinta de Tilcoco',6);
INSERT comunas VALUES(null,'Rengo',6);
INSERT comunas VALUES(null,'Requínoa',6);
INSERT comunas VALUES(null,'San Vicente',6);
INSERT comunas VALUES(null,'Pichilemu',6);
INSERT comunas VALUES(null,'La Estrella',6);
INSERT comunas VALUES(null,'Litueche',6);
INSERT comunas VALUES(null,'Marchihue',6);
INSERT comunas VALUES(null,'Navidad',6);
INSERT comunas VALUES(null,'Paredones',6);
INSERT comunas VALUES(null,'San Fernando',6);
INSERT comunas VALUES(null,'Chépica',6);
INSERT comunas VALUES(null,'Chimbarongo',6);
INSERT comunas VALUES(null,'Lolol',6);
INSERT comunas VALUES(null,'Nancagua',6);
INSERT comunas VALUES(null,'Palmilla',6);
INSERT comunas VALUES(null,'Peralillo',6);
INSERT comunas VALUES(null,'Placilla',6);
INSERT comunas VALUES(null,'Pumanque',6);
INSERT comunas VALUES(null,'Santa Cruz',6);
INSERT comunas VALUES(null,'Talca',7);
INSERT comunas VALUES(null,'Constitución',7);
INSERT comunas VALUES(null,'Curepto',7);
INSERT comunas VALUES(null,'Empedrado',7);
INSERT comunas VALUES(null,'Maule',7);
INSERT comunas VALUES(null,'Pelarco',7);
INSERT comunas VALUES(null,'Pencahue',7);
INSERT comunas VALUES(null,'Río Claro',7);
INSERT comunas VALUES(null,'San Clemente',7);
INSERT comunas VALUES(null,'San Rafael',7);
INSERT comunas VALUES(null,'Cauquenes',7);
INSERT comunas VALUES(null,'Chanco',7);
INSERT comunas VALUES(null,'Pelluhue',7);
INSERT comunas VALUES(null,'Curicó',7);
INSERT comunas VALUES(null,'Hualañé',7);
INSERT comunas VALUES(null,'Licantén',7);
INSERT comunas VALUES(null,'Molina',7);
INSERT comunas VALUES(null,'Rauco',7);
INSERT comunas VALUES(null,'Romeral',7);
INSERT comunas VALUES(null,'Sagrada Familia',7);
INSERT comunas VALUES(null,'Teno',7);
INSERT comunas VALUES(null,'Vichuquén',7);
INSERT comunas VALUES(null,'Linares',7);
INSERT comunas VALUES(null,'Colbún',7);
INSERT comunas VALUES(null,'Longaví',7);
INSERT comunas VALUES(null,'Parral',7);
INSERT comunas VALUES(null,'Retiro',7);
INSERT comunas VALUES(null,'San Javier',7);
INSERT comunas VALUES(null,'Villa Alegre',7);
INSERT comunas VALUES(null,'Yerbas Buenas',7);
INSERT comunas VALUES(null,'Concepción',8);
INSERT comunas VALUES(null,'Coronel',8);
INSERT comunas VALUES(null,'Chiguayante',8);
INSERT comunas VALUES(null,'Florida',8);
INSERT comunas VALUES(null,'Hualqui',8);
INSERT comunas VALUES(null,'Lota',8);
INSERT comunas VALUES(null,'Penco',8);
INSERT comunas VALUES(null,'San Pedro de La Paz',8);
INSERT comunas VALUES(null,'Santa Juana',8);
INSERT comunas VALUES(null,'Talcahuano',8);
INSERT comunas VALUES(null,'Tomé',8);
INSERT comunas VALUES(null,'Hualpén',8);
INSERT comunas VALUES(null,'Lebu',8);
INSERT comunas VALUES(null,'Arauco',8);
INSERT comunas VALUES(null,'Cañete',8);
INSERT comunas VALUES(null,'Contulmo',8);
INSERT comunas VALUES(null,'Curanilahue',8);
INSERT comunas VALUES(null,'Los Álamos',8);
INSERT comunas VALUES(null,'Tirúa',8);
INSERT comunas VALUES(null,'Los Ángeles',8);
INSERT comunas VALUES(null,'Antuco',8);
INSERT comunas VALUES(null,'Cabrero',8);
INSERT comunas VALUES(null,'Laja',8);
INSERT comunas VALUES(null,'Mulchén',8);
INSERT comunas VALUES(null,'Nacimiento',8);
INSERT comunas VALUES(null,'Negrete',8);
INSERT comunas VALUES(null,'Quilaco',8);
INSERT comunas VALUES(null,'Quilleco',8);
INSERT comunas VALUES(null,'San Rosendo',8);
INSERT comunas VALUES(null,'Santa Bárbara',8);
INSERT comunas VALUES(null,'Tucapel',8);
INSERT comunas VALUES(null,'Yumbel',8);
INSERT comunas VALUES(null,'Alto Biobío',8);
INSERT comunas VALUES(null,'Chillán',16);
INSERT comunas VALUES(null,'Bulnes',16);
INSERT comunas VALUES(null,'Cobquecura',16);
INSERT comunas VALUES(null,'Coelemu',16);
INSERT comunas VALUES(null,'Coihueco',16);
INSERT comunas VALUES(null,'Chillán Viejo',16);
INSERT comunas VALUES(null,'El Carmen',16);
INSERT comunas VALUES(null,'Ninhue',16);
INSERT comunas VALUES(null,'Ñiquén',16);
INSERT comunas VALUES(null,'Pemuco',16);
INSERT comunas VALUES(null,'Pinto',16);
INSERT comunas VALUES(null,'Portezuelo',16);
INSERT comunas VALUES(null,'Quillón',16);
INSERT comunas VALUES(null,'Quirihue',16);
INSERT comunas VALUES(null,'Ránquil',16);
INSERT comunas VALUES(null,'San Carlos',16);
INSERT comunas VALUES(null,'San Fabián',16);
INSERT comunas VALUES(null,'San Ignacio',16);
INSERT comunas VALUES(null,'San Nicolás',16);
INSERT comunas VALUES(null,'Treguaco',16);
INSERT comunas VALUES(null,'Yungay',16);
INSERT comunas VALUES(null,'Temuco',9);
INSERT comunas VALUES(null,'Carahue',9);
INSERT comunas VALUES(null,'Cunco',9);
INSERT comunas VALUES(null,'Curarrehue',9);
INSERT comunas VALUES(null,'Freire',9);
INSERT comunas VALUES(null,'Galvarino',9);
INSERT comunas VALUES(null,'Gorbea',9);
INSERT comunas VALUES(null,'Lautaro',9);
INSERT comunas VALUES(null,'Loncoche',9);
INSERT comunas VALUES(null,'Melipeuco',9);
INSERT comunas VALUES(null,'Nueva Imperial',9);
INSERT comunas VALUES(null,'Padre Las Casas',9);
INSERT comunas VALUES(null,'Perquenco',9);
INSERT comunas VALUES(null,'Pitrufquén',9);
INSERT comunas VALUES(null,'Pucón',9);
INSERT comunas VALUES(null,'Saavedra',9);
INSERT comunas VALUES(null,'Teodoro Schmidt',9);
INSERT comunas VALUES(null,'Toltén',9);
INSERT comunas VALUES(null,'Vilcún',9);
INSERT comunas VALUES(null,'Villarrica',9);
INSERT comunas VALUES(null,'Cholchol',9);
INSERT comunas VALUES(null,'Angol',9);
INSERT comunas VALUES(null,'Collipulli',9);
INSERT comunas VALUES(null,'Curacautín',9);
INSERT comunas VALUES(null,'Ercilla',9);
INSERT comunas VALUES(null,'Lonquimay',9);
INSERT comunas VALUES(null,'Los Sauces',9);
INSERT comunas VALUES(null,'Lumaco',9);
INSERT comunas VALUES(null,'Purén',9);
INSERT comunas VALUES(null,'Renaico',9);
INSERT comunas VALUES(null,'Traiguén',9);
INSERT comunas VALUES(null,'Victoria',9);
INSERT comunas VALUES(null,'Valdivia',14);
INSERT comunas VALUES(null,'Corral',14);
INSERT comunas VALUES(null,'Lanco',14);
INSERT comunas VALUES(null,'Los Lagos',14);
INSERT comunas VALUES(null,'Máfil',14);
INSERT comunas VALUES(null,'Mariquina',14);
INSERT comunas VALUES(null,'Paillaco',14);
INSERT comunas VALUES(null,'Panguipulli',14);
INSERT comunas VALUES(null,'La Unión',14);
INSERT comunas VALUES(null,'Futrono',14);
INSERT comunas VALUES(null,'Lago Ranco',14);
INSERT comunas VALUES(null,'Río Bueno',14);
INSERT comunas VALUES(null,'Puerto Montt',10);
INSERT comunas VALUES(null,'Calbuco',10);
INSERT comunas VALUES(null,'Cochamó',10);
INSERT comunas VALUES(null,'Fresia',10);
INSERT comunas VALUES(null,'Frutillar',10);
INSERT comunas VALUES(null,'Los Muermos',10);
INSERT comunas VALUES(null,'Llanquihue',10);
INSERT comunas VALUES(null,'Maullín',10);
INSERT comunas VALUES(null,'Puerto Varas',10);
INSERT comunas VALUES(null,'Castro',10);
INSERT comunas VALUES(null,'Ancud',10);
INSERT comunas VALUES(null,'Chonchi',10);
INSERT comunas VALUES(null,'Curaco de Vélez',10);
INSERT comunas VALUES(null,'Dalcahue',10);
INSERT comunas VALUES(null,'Puqueldón',10);
INSERT comunas VALUES(null,'Queilén',10);
INSERT comunas VALUES(null,'Quellón',10);
INSERT comunas VALUES(null,'Quemchi',10);
INSERT comunas VALUES(null,'Quinchao',10);
INSERT comunas VALUES(null,'Osorno',10);
INSERT comunas VALUES(null,'Puerto Octay',10);
INSERT comunas VALUES(null,'Purranque',10);
INSERT comunas VALUES(null,'Puyehue',10);
INSERT comunas VALUES(null,'Río Negro',10);
INSERT comunas VALUES(null,'San Juan de la Costa',10);
INSERT comunas VALUES(null,'San Pablo',10);
INSERT comunas VALUES(null,'Chaitén',10);
INSERT comunas VALUES(null,'Futaleufú',10);
INSERT comunas VALUES(null,'Hualaihué',10);
INSERT comunas VALUES(null,'Palena',10);
INSERT comunas VALUES(null,'Coyhaique',11);
INSERT comunas VALUES(null,'Lago Verde',11);
INSERT comunas VALUES(null,'Aysén',11);
INSERT comunas VALUES(null,'Cisnes',11);
INSERT comunas VALUES(null,'Guaitecas',11);
INSERT comunas VALUES(null,'Cochrane',11);
INSERT comunas VALUES(null,'O'Higgins',11);
INSERT comunas VALUES(null,'Tortel',11);
INSERT comunas VALUES(null,'Chile Chico',11);
INSERT comunas VALUES(null,'Río Ibáñez',11);
INSERT comunas VALUES(null,'Punta Arenas',12);
INSERT comunas VALUES(null,'Laguna Blanca',12);
INSERT comunas VALUES(null,'Río Verde',12);
INSERT comunas VALUES(null,'San Gregorio',12);
INSERT comunas VALUES(null,'Cabo de Hornos',12);
INSERT comunas VALUES(null,'Antártica',12);
INSERT comunas VALUES(null,'Porvenir',12);
INSERT comunas VALUES(null,'Primavera',12);
INSERT comunas VALUES(null,'Timaukel',12);
INSERT comunas VALUES(null,'Natales',12);
INSERT comunas VALUES(null,'Torres del Paine',12);
INSERT comunas VALUES(null,'Cerrillos',13);
INSERT comunas VALUES(null,'Cerro Navia',13);
INSERT comunas VALUES(null,'Conchalí',13);
INSERT comunas VALUES(null,'El Bosque',13);
INSERT comunas VALUES(null,'Huechuraba',13);
INSERT comunas VALUES(null,'Independencia',13);
INSERT comunas VALUES(null,'La Cisterna',13);
INSERT comunas VALUES(null,'La Granja',13);
INSERT comunas VALUES(null,'La Pintana',13);
INSERT comunas VALUES(null,'La Reina',13);
INSERT comunas VALUES(null,'Las Condes',13);
INSERT comunas VALUES(null,'Lo Barnechea',13);
INSERT comunas VALUES(null,'Lo Espejo',13);
INSERT comunas VALUES(null,'Lo Prado',13);
INSERT comunas VALUES(null,'Macul',13);
INSERT comunas VALUES(null,'Maipú',13);
INSERT comunas VALUES(null,'Ñuñoa',13);
INSERT comunas VALUES(null,'Pedro Aguirre Cerda',13);
INSERT comunas VALUES(null,'Pudahuel',13);
INSERT comunas VALUES(null,'Quilicura',13);
INSERT comunas VALUES(null,'Quinta Normal',13);
INSERT comunas VALUES(null,'Recoleta',13);
INSERT comunas VALUES(null,'Renca',13);
INSERT comunas VALUES(null,'San Joaquín',13);
INSERT comunas VALUES(null,'San Miguel',13);
INSERT comunas VALUES(null,'San Ramón',13);
INSERT comunas VALUES(null,'Vitacura',13);
INSERT comunas VALUES(null,'Pirque',13);
INSERT comunas VALUES(null,'San José de Maipo',13);
INSERT comunas VALUES(null,'Colina',13);
INSERT comunas VALUES(null,'Lampa',13);
INSERT comunas VALUES(null,'Til Til',13);
INSERT comunas VALUES(null,'San Bernardo',13);
INSERT comunas VALUES(null,'Buin',13);
INSERT comunas VALUES(null,'Calera de Tango',13);
INSERT comunas VALUES(null,'Paine',13);
INSERT comunas VALUES(null,'Melipilla',13);
INSERT comunas VALUES(null,'Alhué',13);
INSERT comunas VALUES(null,'Curacaví',13);
INSERT comunas VALUES(null,'María Pinto',13);
INSERT comunas VALUES(null,'San Pedro',13);
INSERT comunas VALUES(null,'Talagante',13);
INSERT comunas VALUES(null,'El Monte',13);
INSERT comunas VALUES(null,'Isla de Maipo',13);
INSERT comunas VALUES(null,'Padre Hurtado',13);
INSERT comunas VALUES(null,'Peñaflor',13);
INSERT comunas VALUES(null,'Arica',15);
INSERT comunas VALUES(null,'Camarones',15);
INSERT comunas VALUES(null,'Putre',15);
INSERT comunas VALUES(null,'General Lagos',15);